name: Run generateBuild.py on commit

# Trigger this workflow on commits pushed to the main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generateBuild.py
        run: |
          python generateBuild.py

      # Step 5: Commit and push changes to the build folder (optional)
      - name: Commit and push build folder
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add build/
          git commit -m "Update build folder [skip ci]" || echo "No changes to commit"
          git push origin main
